extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
plugins:
  - react
rules:
  semi:
    - error
    - always
  quotes:
    - error
    - single
  indent:
    - error
    - 2
    - SwitchCase: 1
  arrow-parens:
    - error
    - as-needed
  react/prop-types:
    - off
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
env:
  node: true
  browser: true
  es6: true
  commonjs: true
parser: babel-eslint
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  allowImportExportEverywhere: false
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
